version: "3"

services:
  local-db:
    image: postgres
    hostname: local-db
    container_name: local-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: newsletter
      POSTGRES_PASSWORD: welcome
      POSTGRES_DB: newsletter
    command: postgres -c "max_connections=1000"
