[workspace]
resolver = "2"
members = [
  "runner",
  "interface/api",
  "infrastructure/repositories",
  "infrastructure/messengers",
  "domain",
  "tests",
]

[workspace.lints.rust]
unsafe_code = "forbid"
