version: "3"

services:
  subscription-local-db:
    image: postgres
    hostname: subscription-local-db
    container_name: subscription-local-db
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: subscription
      POSTGRES_PASSWORD: welcome
      POSTGRES_DB: subscription
    command: postgres -c "max_connections=1000"
