[workspace]
resolver = "2"
members = [
  "runner",
  "interface/api",
  "infrastructure/gateways",
  "domain",
  "tests", "infrastructure/repositories",
]

[workspace.lints.rust]
unsafe_code = "forbid"
