api:
  listening:
    host: 127.0.0.1
    port: 28080

database:
  source:
    engine: PostgreSQL
    host: 127.0.0.1
    port: 25432
    username: publication
    password: welcome
    database: publication
  pool_options:
    min_connections: 2
    max_connections: 2
    connect_timeout: 3 # seconds

gateways:
  subscription:
    origin: http://127.0.0.1:18080

logging:
  global: info
  crates:
    # api: info
    # gateways: warn
    sqlx: debug
