default:
	just --list

test: sqlx-migrate
	cargo test

test-with-log: sqlx-migrate
	TEST_LOG=true cargo test | bunyan

build:
	cargo build

run: sqlx-migrate
	cargo run | bunyan

sqlx-prepare:
	cargo sqlx prepare --database-url postgres://publication:welcome@localhost:25432/publication --workspace

watch-run: sqlx-migrate
	cargo watch -x run | bunyan

container-up:
	docker compose up -d

container-down:
	docker compose down

sqlx-migrate:
	sqlx migrate run --database-url postgres://publication:welcome@localhost:25432/publication --source infrastructure/repositories/migrations

fmt:
	cargo +nightly fmt

fmt-check:
	cargo +nightly fmt --check

lint-check:
	cargo clippy -- -D warnings

find-unused:
	cargo +nightly udeps --all-targets --quiet
